name: 'Run Testbox'
description: 'Keeps the testbox runner alive until idle timeout. Reads config from the state directory written by useblacksmith/begin-testbox.'

runs:
  using: 'composite'
  steps:
    - name: Run Testbox
      shell: bash
      run: |
        STATE=/tmp/.testbox
        if [ ! -d "$STATE" ]; then
          echo "Error: No testbox state found. Did you run useblacksmith/begin-testbox first?"
          exit 1
        fi

        TESTBOX_ID=$(cat "$STATE/testbox_id")
        INSTALLATION_MODEL_ID=$(cat "$STATE/installation_model_id")
        AUTH_TOKEN=$(cat "$STATE/auth_token")
        IDLE_TIMEOUT=$(cat "$STATE/idle_timeout" 2>/dev/null)
        IDLE_TIMEOUT="${IDLE_TIMEOUT:-10}"
        API_URL=$(cat "$STATE/api_url")
        RUNNER_HOST=$(cat "$STATE/runner_host")
        RUNNER_SSH_PORT=$(cat "$STATE/runner_ssh_port")
        WORKING_DIRECTORY=$(cat "$STATE/working_directory")
        ADOPTED_RUN_ID=$(cat "$STATE/adopted_run_id")

        # Phone home (ready)
        curl -s -f -X POST "${API_URL}/api/testbox/phone-home" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${AUTH_TOKEN}" \
          -d "{
            \"testbox_id\": \"${TESTBOX_ID}\",
            \"installation_model_id\": ${INSTALLATION_MODEL_ID},
            \"status\": \"ready\",
            \"ip_address\": \"${RUNNER_HOST}\",
            \"ssh_port\": \"${RUNNER_SSH_PORT}\",
            \"working_directory\": \"${WORKING_DIRECTORY}\",
            \"adopted_run_id\": \"${ADOPTED_RUN_ID}\",
            \"metadata\": {}
          }" || echo "Warning: phone-home (ready) failed, continuing in degraded mode"
        echo "Phone-home (ready) complete."

        echo "============================================"
        echo "Testbox ready!"
        echo "  Testbox ID:         ${TESTBOX_ID}"
        echo "  Runner host:        ${RUNNER_HOST}"
        echo "  SSH port:           ${RUNNER_SSH_PORT}"
        echo "  Working directory:  ${WORKING_DIRECTORY}"
        echo "  Run ID:             ${ADOPTED_RUN_ID}"
        echo "  SSH:                ssh -p ${RUNNER_SSH_PORT} runner@${RUNNER_HOST}"
        echo "============================================"

        # Idle timeout monitoring loop
        #
        # Hybrid activity detection:
        #   1. Active SSH connections to the runner port (catches interactive
        #      sessions, long-running commands, rsync transfers)
        #   2. Marker file ~/.testbox-last-activity (the Blacksmith CLI
        #      touches this on every `testbox run` invocation)
        #
        # Any signal resets the idle timer. Shutdown only happens after the
        # full idle_timeout elapses with zero activity from either source.

        LAST_ACTIVITY=$(date +%s)
        IDLE_TIMEOUT_SECONDS=$(( IDLE_TIMEOUT * 60 ))

        while true; do
          sleep 30

          NOW=$(date +%s)

          if ss -tnp 2>/dev/null | grep -q ":${RUNNER_SSH_PORT}\b" ; then
            LAST_ACTIVITY=$NOW
          elif [ -f ~/.testbox-last-activity ]; then
            FILE_MTIME=$(stat -c %Y ~/.testbox-last-activity)
            if [ "$FILE_MTIME" -gt "$LAST_ACTIVITY" ]; then
              LAST_ACTIVITY=$FILE_MTIME
            fi
          fi

          IDLE_SECONDS=$(( NOW - LAST_ACTIVITY ))

          if [ "$IDLE_SECONDS" -ge "$IDLE_TIMEOUT_SECONDS" ]; then
            echo "Idle timeout reached (${IDLE_TIMEOUT} minutes). Shutting down."
            exit 0
          fi
        done
